name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.401
      - name: Build
        run: ./scripts/build.sh
      - name: Test
        run: ./scripts/cover.sh
      - shell: bash
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          PACKAGES_API_KEY: ${{secrets.PACKAGES_API_KEY}}
        run: ./scripts/publish.sh "${GITHUB_REF#refs/tags/v}" "$NUGET_API_KEY" "$PACKAGES_API_KEY"
